### ISSUE TITLE
Feature Request: autocomplete Support in brackets also when changing existing definitions

### ISSUE THREAD

**Issue by Keridos** [Yesterday17/ZenScript#14]
Detect changes in bracket definitions and provide autocomplete when not starting a new definition only.

**Comment by Yesterday17** [comment]
Sorry...  Could you describe it in detail?

**Comment by Yesterday17** [comment]
If you're looking for a way to trigger autocompletion manually, you can try <kbd>Ctrl</kbd> + <kbd>Space</kbd>. It's provided by vscode itself.

**Comment by Keridos** [comment]
That might help yeah. I noticed that if you have an existing bracket definition like <minecraft:apple> and you proceed to delete apple from that and start typing, autocomplete does not start (only shows matches from the rest of the text, with the ABC icon).

**Comment by Yesterday17** [comment]
That's because autocomplete must be **triggered**. There're two ways to trigger an autocomplete: **character** and manual trigger. When you type in characters such as `:`, autocompletion is triggered. It would use lots of resource if every type can trigger autocompletion.
This problem will not be fixed. It's an intensionally designed 'feature'.
